version: "3"
services:
  traefik:
    image: "traefik:v3.3"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/tutina"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.asdefault=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/traefik.yml:/etc/tutina/traefik.yml:ro"
  app:
    image: "jasujm/tutina"
    build: "."
    env_file:
      - "./.env.tutina"
    depends_on:
      - "db"
    volumes:
      - "./env/tutina.toml:/etc/tutina.toml:ro"
      - "./env/data:/usr/share/tutina:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.middlewares=securityHeaders@file"
      - "traefik.http.routers.app.rule=PathPrefix(`/`)"
  db:
    image: "mariadb:11"
    volumes:
      - "dbdata:/var/lib/mysql"
    env_file:
      - "./.env.db"
volumes:
  dbdata:
