name: "Tutina"
description: "Tools for predicting and controlling indoor temperature"
version: "0.4"
slug: "tutina"
init: false
arch:
  - aarch64
options:
  owm_api_key: null
  owm_coordinates:
    lon: null
    lat: null
  tutina_base_url: null
  tutina_token_secret: null
schema:
  owm_api_key: str
  owm_coordinates:
    lon: float
    lat: float
  tutina_base_url: url
  tutina_token_secret: str
homeassistant_api: true
services:
  - mysql:need
