version: "3"
services:
  traefik:
    image: "traefik:v3.3"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:8080"
    ports:
      - "80:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  app:
    image: "jasujm/tutina"
    build: "."
    env_file:
      - "./.env.tutina"
    depends_on:
      - "db"
    volumes:
      - "${TUTINA_CONFIG_FILE}:/etc/tutina.toml:ro"
      - "${TUTINA_DATA_DIR}:/usr/share/tutina:rw"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.routers.app.rule=PathPrefix(`/`)"
  db:
    image: "mariadb:11"
    volumes:
      - "dbdata:/var/lib/mysql"
    env_file:
      - "./.env.db"
volumes:
  dbdata:
